#!/bin/bash
set -o errexit

DOMAIN=${1:-magento.test}
VERSION=${2:-2.4.2}
EDITION=${3:-enterprise}

curl -s https://raw.githubusercontent.com/ParkYongGyu/magento2.4.2-php7.4-order/main/lib/template | bash

# &&'s are used below otherwise onelinesetup script fails/errors after bin/download
bin/download "${VERSION}" "${EDITION}" \
  && bin/setup "${DOMAIN}"
